# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jpy_sandbox',
                'doc_host': 'https://fuzzyalej.github.io',
                'git_url': 'https://github.com/fuzzyalej/jpy_sandbox',
                'lib_path': 'jpy_sandbox'},
  'syms': {'jpy_sandbox.core': {'jpy_sandbox.core.foo': ('core.html#foo', 'jpy_sandbox/core.py')}}}
